/**
 * Writes docs/PARAMETERS.md from the parameter definitions, so the reference
 * never drifts from the code.   npm run params
 */
import { writeFileSync } from 'node:fs';
import { DEFAULT_TUNING, TUNING_SPEC, defaultsForAge, getParam } from '../src/index.ts';

const GROUPS: Record<string, string> = {
  retention: 'Target recall',
  workload: 'Workload',
  ladder: 'Question ladder',
  planner: 'Session planner',
  session: 'Inside a session',
  mission: 'Missions',
  reminders: 'Reminders',
  memory: 'Memory model',
  byHeart: 'Learning by heart',
  concentration: 'Concentration profile',
};

const bands = [
  ['Children 10–11', defaultsForAge(10)],
  ['Children 12–13', defaultsForAge(12)],
  ['Parents', defaultsForAge(40)],
] as const;
const range = (r: readonly number[]) => `${r[0]}–${r[1]}`;

const lines: string[] = [
  '# Parameters',
  '',
  '<!-- Generated by `npm run params` from packages/engine/src/tuning.ts and profiles.ts. Edit those, not this file. -->',
  '',
  'Every fine-tuning knob of the engine, with its default, the range a family can choose from, and why the default is what it is. Values outside the range are clamped.',
  '',
  '## Per learner: set by the family',
  '',
  '| Setting | ' + bands.map(([name]) => name).join(' | ') + ' |',
  '|---|' + bands.map(() => '---').join('|') + '|',
  '| Session length, minutes: default (range) | ' + bands.map(([, b]) => `${b.sessionMinutes} (${range(b.sessionRange)})`).join(' | ') + ' |',
  '| Sessions per day: default (range) | ' + bands.map(([, b]) => `${b.sessionsPerDay} (${range(b.sessionsPerDayRange)})`).join(' | ') + ' |',
  '| Minimum break between sessions, minutes | ' + bands.map(([, b]) => b.minGapMinutes).join(' | ') + ' |',
  '| New units per day, at most | ' + bands.map(([, b]) => b.maxNewPerDay).join(' | ') + ' |',
  '| Reminders per day, at most | ' + bands.map(([, b]) => b.maxRemindersPerDay).join(' | ') + ' |',
  '| Answer modes | ' + bands.map(([, b]) => b.answerModes.join(', ')).join(' | ') + ' |',
  '| Who sees progress | ' + bands.map(([, b]) => (b.visibility === 'family' ? 'parents and child, same view' : 'only the learner')).join(' | ') + ' |',
  '',
  '## Engine tuning: same for the whole family unless changed',
  '',
];

for (const [group, title] of Object.entries(GROUPS)) {
  lines.push(`### ${title}`, '', '| Parameter | Default | Range | Why |', '|---|---|---|---|');
  for (const spec of TUNING_SPEC.filter((s) => s.path.startsWith(`${group}.`))) {
    lines.push(`| ${spec.label} <br>\`${spec.path}\` | ${getParam(DEFAULT_TUNING, spec.path)} | ${spec.min}–${spec.max} | ${spec.why} |`);
  }
  lines.push('');
}

const out = new URL('../../../docs/PARAMETERS.md', import.meta.url);
writeFileSync(out, lines.join('\n'));
console.log(`Wrote ${TUNING_SPEC.length} engine parameters and ${bands.length} learner bands to docs/PARAMETERS.md`);
