"""Writes docs/PARAMETERS.md from the parameter definitions, so the reference
never drifts from the code.

    uv run packages/engine/scripts/params.py
"""

from pathlib import Path

from lc_engine import DEFAULT_TUNING, TUNING_SPEC, defaults_for_age, get_param

GROUPS = {
    "retention": "Target recall",
    "workload": "Workload",
    "ladder": "Question ladder",
    "planner": "Session planner",
    "session": "Inside a session",
    "mission": "Missions",
    "reminders": "Reminders",
    "memory": "Memory model",
    "by_heart": "Learning by heart",
    "concentration": "Concentration profile",
}

BANDS = [("Children 10–11", defaults_for_age(10)), ("Children 12–13", defaults_for_age(12)), ("Parents", defaults_for_age(40))]


def number(x: float) -> str:
    return str(int(x)) if float(x).is_integer() else str(x)


def span(r: tuple[float, float]) -> str:
    return f"{number(r[0])}–{number(r[1])}"


def row(label: str, values: list[str]) -> str:
    return f"| {label} | {' | '.join(values)} |"


lines = [
    "# Parameters",
    "",
    "<!-- Generated by `uv run packages/engine/scripts/params.py` from packages/engine/src/lc_engine/tuning.py"
    " and profiles.py. Edit those, not this file. -->",
    "",
    "Every fine-tuning knob of the engine, with its default, the range a family can choose from, and why the default"
    " is what it is. Values outside the range are clamped.",
    "",
    "## Per learner: set by the family",
    "",
    row("Setting", [name for name, _ in BANDS]),
    "|---|" + "|".join("---" for _ in BANDS) + "|",
    row("Session length, minutes: default (range)", [f"{b.session_minutes} ({span(b.session_range)})" for _, b in BANDS]),
    row("Sessions per day: default (range)", [f"{b.sessions_per_day} ({span(b.sessions_per_day_range)})" for _, b in BANDS]),
    row("Minimum break between sessions, minutes", [str(b.min_gap_minutes) for _, b in BANDS]),
    row("New units per day, at most", [str(b.max_new_per_day) for _, b in BANDS]),
    row("Reminders per day, at most", [str(b.max_reminders_per_day) for _, b in BANDS]),
    row("Answer modes", [", ".join(b.answer_modes) for _, b in BANDS]),
    row(
        "Who sees progress",
        ["parents and child, same view" if b.visibility == "family" else "only the learner" for _, b in BANDS],
    ),
    "",
    "## Engine tuning: same for the whole family unless changed",
    "",
]

for group, title in GROUPS.items():
    lines += [f"### {title}", "", "| Parameter | Default | Range | Why |", "|---|---|---|---|"]
    for spec in (s for s in TUNING_SPEC if s.path.startswith(f"{group}.")):
        default = number(get_param(DEFAULT_TUNING, spec.path))
        lines.append(f"| {spec.label} <br>`{spec.path}` | {default} | {number(spec.min)}–{number(spec.max)} | {spec.why} |")
    lines.append("")

out = Path(__file__).resolve().parents[3] / "docs" / "PARAMETERS.md"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {len(TUNING_SPEC)} engine parameters and {len(BANDS)} learner bands to docs/PARAMETERS.md")
