"""Use case 2 end to end, on the sample maths map:

  parents push "solving linear equations" to their 13-year-old's app
  -> a short placement check finds which prerequisites are missing
  -> the learning path (missing prerequisites first) becomes a mission
  -> the learner picks the mission; three short sessions that day

    uv run packages/engine/scripts/push.py

Answers come from a synthetic learner; in the app, the units of each notion
come from teach_notion() in packages/ingest and go through the review inbox.
"""

import random
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from lc_engine import (
    AdaptiveScheduler,
    ItemState,
    KnowledgeMap,
    KnowledgeUnit,
    Latency,
    LearnerProfile,
    MemoryModel,
    PlacementCheck,
    Rating,
    defaults_for_age,
    mission_progress,
    next_useful_time,
    plan_session,
    pushed_mission,
    seeded_rng,
    to_focus,
)

random.seed(7)  # interval fuzz
PARIS = ZoneInfo("Europe/Paris")
maths = KnowledgeMap.load("maths-core")
target = "linear-equations"
truth_known = {
    "whole-numbers",
    "multiplication-facts",
    "division",
    "order-of-operations",
    "decimals",
    "fractions-meaning",
    "equivalent-fractions",
}

# 1. Placement check over the target and everything it builds on.
print(f'\nParents push: "{maths.get(target).title}" (Léa, 13)\n\n1. Placement check')
check = PlacementCheck(maths, [target, *maths.ancestors(target)])
while (notion := check.next()) is not None:
    passed = notion.id in truth_known
    print(f'   asks about "{notion.title}" → {"passed" if passed else "missed"}')
    check.record(notion.id, passed)
placed = check.result()
settled = len(placed.known) + len(placed.unknown)
print(f"   {placed.asked} questions settled {settled} notions: {len(placed.unknown)} missing")

# 2. Learning path: missing prerequisites first.
path = maths.learning_path([target], lambda nid: nid in placed.known)
print("\n2. Learning path (becomes the mission)")
for i, n in enumerate(path, 1):
    print(f"   {i}. {n.title}")

# 3. Units per notion (in the app: generated by teach_notion, checked in the review inbox).
path_ids = {n.id for n in path}
units = [
    KnowledgeUnit(
        id=f"{n.id}/{k}",
        subject="Maths",
        kind="procedure",
        title=f"{n.title} #{k}",
        notion_id=n.id,
        # The first unit of a notion builds on the first unit of each missing prerequisite; the others on their own first unit.
        prerequisites=[f"{p}/1" for p in n.prerequisites if p in path_ids] if k == 1 else [f"{n.id}/1"],
    )
    for n in path
    for k in (1, 2, 3)
]
items = [ItemState(ku) for ku in units]
mission = pushed_mission(target, f"Before high school: {maths.get(target).title}", [n.id for n in path], items, "your parents")

# 4. One day: three short sessions, each focused on the mission.
band = defaults_for_age(13)
lea = LearnerProfile(
    id="lea",
    name="Léa",
    session_minutes=band.session_minutes,
    sessions_per_day=3,
    min_gap_minutes=band.min_gap_minutes,
    max_new_per_day=band.max_new_per_day,
    seconds_per_probe={"recognize": 15, "recall": 25, "apply": 40, "explain": 50},
    latency_ms=Latency(4000, 12000),
    recent_accuracy=0.85,
)
memory = MemoryModel(same_day_gap_minutes=lea.min_gap_minutes)
scheduler = AdaptiveScheduler(memory)
rng = seeded_rng(7)
new_today = 0

print(f'\n3. Mission "{mission.title}": {len(mission.ku_ids)} units')
for hour, minute in ((9, 0), (10, 45), (17, 30)):
    now = datetime(2026, 10, 3, hour, minute, tzinfo=PARIS)
    plan = plan_session(lea, items, [], now, memory, focus=to_focus(mission), new_today=new_today)
    kinds = [(k, sum(1 for i in plan.items if i.kind == k)) for k in ("repair", "review", "new", "practice")]
    summary = ", ".join(f"{n} {k}" for k, n in kinds if n) or "nothing useful yet"
    print(f"   {hour:02}:{minute:02} session: {len(plan.items)} cards, ~{plan.minutes} min ({summary})")
    by_id = {i.ku.id: i for i in items}
    for p in plan.items:
        grade = Rating.Good if rng() < 0.85 else Rating.Again
        if p.kind == "new":
            new_today += 1
        by_id[p.ku_id] = ItemState(by_id[p.ku_id].ku, scheduler.record(by_id[p.ku_id], now, grade))
    items = [by_id[i.ku.id] for i in items]
    nxt = next_useful_time(items, now + timedelta(minutes=plan.minutes))
    if nxt is not None:
        print(f"      next useful session: {nxt:%H:%M}{' tomorrow' if nxt.date() != now.date() else ''}")

p = mission_progress(mission, items, memory, datetime(2026, 10, 3, 18, 0, tzinfo=PARIS))
print(
    f"\n4. End of day: {p.started} of {p.total} units started, {p.secure} secure (secure needs correct answers on separate days)\n"
)
