/**
 * Use case 2 end to end, on the sample maths map:
 *
 *   parents push "solving linear equations" to their 13-year-old's app
 *   → a short placement check finds which prerequisites are missing
 *   → the learning path (missing prerequisites first) becomes a mission
 *   → the child picks the mission; three short sessions that day
 *
 *   npm run push
 *
 * Answers come from a synthetic learner; in the app, the units of each notion
 * come from teachNotion() in packages/ingest and go through the review inbox.
 */
import { Rating } from 'ts-fsrs';
import notions from '../maps/maths-core.json' with { type: 'json' };
import {
  AdaptiveScheduler,
  KnowledgeMap,
  MemoryModel,
  PlacementCheck,
  defaultsForAge,
  pushedMission,
  missionProgress,
  nextUsefulTime,
  planSession,
  seededRng,
  toFocus,
  type ItemState,
  type KnowledgeUnit,
  type LearnerProfile,
  type Notion,
} from '../src/index.ts';

const map = new KnowledgeMap(notions as Notion[]);
const target = 'linear-equations';
const truthKnown = new Set(['whole-numbers', 'multiplication-facts', 'division', 'order-of-operations', 'decimals', 'fractions-meaning', 'equivalent-fractions']);

// 1. Placement check over the target and everything it builds on.
console.log(`\nParents push: "${map.get(target).title}" (Léa, 13)\n\n1. Placement check`);
const check = new PlacementCheck(map, [target, ...map.ancestors(target)]);
for (let n = check.next(); n; n = check.next()) {
  const passed = truthKnown.has(n.id);
  console.log(`   asks about "${n.title}" → ${passed ? 'passed' : 'missed'}`);
  check.record(n.id, passed);
}
const placed = check.result();
console.log(`   ${placed.asked} questions settled ${placed.known.length + placed.unknown.length} notions: ${placed.unknown.length} missing`);

// 2. Learning path: missing prerequisites first.
const path = map.learningPath([target], (id) => placed.known.includes(id));
console.log('\n2. Learning path (becomes the mission)');
path.forEach((n, i) => console.log(`   ${i + 1}. ${n.title}`));

// 3. Units per notion (in the app: generated by teachNotion, checked in the review inbox).
const pathIds = new Set(path.map((n) => n.id));
const units: KnowledgeUnit[] = path.flatMap((n) =>
  [1, 2, 3].map((k) => ({
    id: `${n.id}/${k}`,
    subject: 'Maths',
    kind: 'procedure' as const,
    title: `${n.title} #${k}`,
    importance: 2 as const,
    notionId: n.id,
    // The first unit of a notion builds on the first unit of each missing prerequisite; the others on their own first unit.
    prerequisites: k === 1 ? n.prerequisites.filter((p) => pathIds.has(p)).map((p) => `${p}/1`) : [`${n.id}/1`],
    goalIds: [],
    cumulative: true,
  })),
);
let items: ItemState[] = units.map((ku) => ({ ku }));
const mission = pushedMission(target, `Before high school: ${map.get(target).title}`, path.map((n) => n.id), items, 'your parents');

// 4. One day: three short sessions, each focused on the mission.
const band = defaultsForAge(13);
const lea: LearnerProfile = {
  id: 'lea',
  name: 'Léa',
  sessionMinutes: band.sessionMinutes,
  sessionsPerDay: 3,
  minGapMinutes: band.minGapMinutes,
  maxNewPerDay: band.maxNewPerDay,
  secondsPerProbe: { recognize: 15, recall: 25, apply: 40, explain: 50 },
  latencyMs: { p25: 4000, p75: 12000 },
  recentAccuracy: 0.85,
};
const memory = new MemoryModel(undefined, { sameDayGapMinutes: lea.minGapMinutes });
const scheduler = new AdaptiveScheduler(memory, []);
const rng = seededRng(7);
let newToday = 0;

console.log(`\n3. Mission "${mission.title}": ${mission.kuIds.length} units`);
for (const time of ['09:00', '10:45', '17:30']) {
  const [h, m] = time.split(':').map(Number);
  const now = new Date(2026, 9, 3, h, m);
  const plan = planSession({ learner: lea, items, goals: [], now, memory, focus: toFocus(mission), newToday });
  const kinds = ['repair', 'review', 'new', 'practice'].map((k) => [k, plan.items.filter((i) => i.kind === k).length] as const).filter(([, n]) => n);
  console.log(`   ${time} session: ${plan.items.length} cards, ~${plan.minutes} min (${kinds.map(([k, n]) => `${n} ${k}`).join(', ') || 'nothing useful yet'})`);
  for (const p of plan.items) {
    const item = items.find((i) => i.ku.id === p.kuId)!;
    const grade = rng() < 0.85 ? Rating.Good : Rating.Again;
    if (p.kind === 'new') newToday++;
    items = items.map((i) => (i === item ? { ...i, card: scheduler.record(item, now, grade) } : i));
  }
  const next = nextUsefulTime(items, new Date(now.getTime() + plan.minutes * 60_000));
  if (next) console.log(`      next useful session: ${next.toTimeString().slice(0, 5)}${next.getDate() !== now.getDate() ? ' tomorrow' : ''}`);
}
const p = missionProgress(mission, items, memory, new Date(2026, 9, 3, 18, 0));
console.log(`\n4. End of day: ${p.started} of ${p.total} units started, ${p.secure} secure (secure needs correct answers on separate days)\n`);
